export declare enum ECHATMETHOD {
    NEW_PEER = "newPeer",
    NEW_MAIN_PEER = "newMainPeer",
    PEER_CLOSE = "peerClosed",
    MAIN_PEER_CLOSE = "mainPeerClosed",
    JOIN = "join",
    CLOSE_PEER = "closePeer",
    GET_MESSAGES = "getMessages",
    CHAT_MESSAGE = "chatMessage",
    DELETE_MESSAGE = "deleteMessage",
    UPDATE_ROOM = "updateRoom",
    DELETE_ROOM = "deleteRoom",
    UPDATE_STATUS = "updateStatus",
    PEER_UPDATE = "updatePeer",
    SOCKET_CONNECTED = "socketConnected",
    SOCKET_DISCONNECTED = "socketDisconnected",
    NEW_ROOM = "newRoom",
    ROOM_CREATED = "roomCreated",
    UPDATE_ROOMS_ON_NEW = "updateRoomOnNew"
}
